version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always

    app:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        restart: always
